# Sample .travis.yml for R projects

dist: trusty
language: r
warnings_are_errors: true
sudo: required
addons:
  apt:
    packages:
      - libgsl0-dev
      - libgsl2
r_binary_packages:
 - testthat
 - knitr
 - rmarkdown
 - gsl
 - evd
 - msm
 - dplyr
 - tidyr
 - latticeExtra

